name = input("What is your name? ")
print("Hi", name)
team = input("What is your favorite sport team? ")
worl = input("Do you think " + team + " will win this season? ")
print("Thank you for your input!")